### ISSUE TITLE
question: react template for chrome app

### ISSUE THREAD

**Issue by sagivo** [olineham/react-chrome-app-window#1]
is there a template i can find of how to set react with chrome app?

**Comment by olineham** [comment]
Sadly, Chrome Apps were retired from Chrome: https://blog.chromium.org/2016/08/from-chrome-apps-to-web.html
Don't waste your effort developing new ones - they won't work anymore, sometime in 2018.

**Comment by sagivo** [comment]
holy &^&()@
you just made (and ruined) my day!
thanks
